apiVersion: v1
kind: Namespace
metadata:
  name: lab04
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    org: webserver
    app: nginx
  name: nginx
  namespace: lab04
spec:
  replicas: 2
  selector:
    matchLabels:
      org: webserver
      app: nginx
  template:
    metadata:
      labels:
        org: webserver
        app: nginx
    spec:
      containers:
      - image: nginx:1.27-alpine
        name: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    org: webserver
    app: apache
  name: apache
  namespace: lab04
spec:
  replicas: 2
  selector:
    matchLabels:
      org: webserver
      app: apache
  template:
    metadata:
      labels:
        org: webserver
        app: apache
    spec:
      containers:
      - image: httpd:2.4-alpine
        name: apache
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    org: webserver
    app: agnhost
  name: agnhost
  namespace: lab04
spec:
  replicas: 4
  selector:
    matchLabels:
      org: webserver
      app: agnhost
  template:
    metadata:
      labels:
        org: webserver
        app: agnhost
    spec:
      containers:
      - image: registry.k8s.io/e2e-test-images/agnhost:2.53
        name: agnhost
        args:
        - serve-hostname
        - --port
        - "80"
        ports:
        - containerPort: 80
