apiVersion: v1
kind: Pod
metadata:
  name: my-app
  namespace: lab05
spec:
  containers:
  - name: my-app
    image: busybox
    command: ["sh", "-c", "echo 'Hello from PVC' > /data/message.txt; sleep 3600"]
    volumeMounts:
    - mountPath: /data
      name: storage
  volumes:
  - name: storage
    persistentVolumeClaim:
      claimName: my-pvc
