apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
  namespace: lab05
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
