---
apiVersion: v1
kind: Namespace
metadata:
  name: lab05
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
  namespace: lab05
data:
  APP_MODE: production
  LOG_LEVEL: info
---
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  namespace: lab05
type: Opaque
data:
  DB_USER: YWRtaW4=  # base64 encoded 'admin'
  DB_PASS: c3VwZXJzZWNyZXQ=  # base64 encoded 'supersecret'

