apiVersion: v1
kind: Pod
metadata:
  name: agnhost
  namespace: kube-public
spec:
  containers:
  - name: agnhost
    image: registry.k8s.io/e2e-test-images/agnhost:2.53
    ports:
    - containerPort: 80
