apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: tico-agnhost
  name: tico-agnhost
  namespace: kube-public
spec:
  containers:
  - image: registry.k8s.io/e2e-test-images/agnhost:2.53
    name: tico-agnhost
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
